config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'budget_details/index'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # for setting up a default page
  root 'welcome#index'
  # or rails < 4
  # root to: 'welcome#index'
  # get 'welcome/index'
  get '/plan/:budget_plan_id/expenses(.:format)', to: 'expenses#index', as: 'my_expenses'
  get '/plans(.:format)', to: 'budget_plans#index'

  #
  # Users
  #
  resources :users do
    resources :budget_plans do
      resources :expenses
      resources :budget_details
    end
  end
  #
  # Session and Authentication routes
  # Remapping route
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  # get 'users/index'
  # get 'users/new'
  # get 'users/edit'
  # get 'users/show'

  #
  # Categories
  #
  get '/categories', to: 'categories#index'
  # get '/json/categories', to: 'categories#catjson'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true
class WelcomeController < ApplicationController
  def index
    # This action should list users budgets
    # if current_user
    #   @plans = BudgetPlans.all
    #   respond_to do |format|
    #     format.html
    #     # as_json or to_json??
    #     format.json { render(json: @plans.as_json(only: %i[id f_name l_name email user_name])) }
    #   end
    # end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="main-card" class="main-card">
        
        <div class="cardContent">
          <div class="cardText">
            <p style="color: green; text-align: right;"><%=flash[:notice]%></p>
            <% if current_user %>
            <div class="log-out">
              Logged in as <%= current_user.f_name %>
              <%= link_to "Log Out", logout_path, class: 'links' %>
            </div>
            <% end %>
            <h1>Welcome to BudgetCop!</h1>
            <% if current_user && current_user.admin %>
              <div class="nav-bar">
                <%= link_to "Users", users_path, class: 'links' %>
              </div>
            <% end %>
            <hr/>
            <p class="main-p"><span class="p-app-name">BudgetCop</span> was founded <em>Dipti Rijwal</em>, <em>Juanita Dash</em> and <em>Peter Studnicka</em> while they were development interns at <strong>Shopify</strong>. This faboulous group
            was part of the original Welcome Back Group, an original undertaking by the RnD arm at Shopify.</p>
          </div>
          <div class="cardLinks">
            <% if !current_user %>
              <%= link_to "Log In", login_path, class: 'links' %> |
              <%= link_to "Sign up", new_user_path, class: 'links' %>
            <% end %>
          </div>
        </div>

<p><em style="font-size: 0.7em;">Copyright 2019</em></p>
</div>